"use client";
import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    padding: 30,
  },
  header: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#000",
    paddingBottom: 5,
    marginBottom: 10,
  },
  headerText: {
    fontSize: 16,
    fontWeight: "bold",
    flex: 1,
    textAlign: "center",
  },
  row: {
    flexDirection: "row",
    marginBottom: 5,
  },
  cell: {
    fontSize: 4,
    flex: 1,
    textAlign: "center",
  },
  title: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 10,
  },
});

const PDFReport = ({ orders, fromDate, toDate, generatedBy }) => {
  // Calculate total orders, total bill amount, and total net amount
  const totalOrders = orders.length;
  const totalBillAmount = orders.reduce(
    (total, order) => total + order.totalBillAmount,
    0
  );
  const totalNetAmount = totalBillAmount - totalOrders * 0; // Assuming discount amount is always 0

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={{ flexDirection: "row", justifyContent: "center" }}>
          <Text style={{ fontSize: 14, fontWeight: "bold" }}>
            CITY HEALTH CARE
          </Text>
        </View>
        <Text style={styles.title}>Daily Collection Report</Text>
        <View style={styles.header}>
          <Text style={styles.headerText}>Sl No.</Text>
          <Text style={styles.headerText}>Bill No.</Text>
          <Text style={styles.headerText}>Patient Name</Text>
          <Text style={styles.headerText}>Bill Amt</Text>
          <Text style={styles.headerText}>Disc Amt</Text>
          <Text style={styles.headerText}>Net At</Text>
          <Text style={styles.headerText}>Due Amt</Text>
          <Text style={styles.headerText}>Rec Amt</Text>
          <Text style={styles.headerText}>Centre</Text>
        </View>
        {orders.map((order, index) => (
          <View style={styles.row} key={order.billNumber + index}>
            <Text style={styles.cell}>{index + 1}</Text>
            <Text style={styles.cell}>{order.billNumber}</Text>
            <Text style={styles.cell}>{order.basicInfo.firstName}</Text>
            <Text style={styles.cell}>{order.totalBillAmount}</Text>
            <Text style={styles.cell}>0</Text>{" "}
            {/* Assuming discount amount is always 0 */}
            <Text style={styles.cell}>{order.totalBillAmount}</Text>{" "}
            {/* Net Amount */}
            <Text style={styles.cell}>0</Text>{" "}
            {/* Assuming Due Amount is always 0 */}
            <Text style={styles.cell}>0</Text>{" "}
            {/* Assuming Rec Amount is always 0 */}
            <Text style={styles.cell}>{order.services[0].centerName}</Text>
          </View>
        ))}
        <View style={styles.row}>
          <Text style={styles.cell}>Total Orders: {totalOrders}</Text>
          <Text style={styles.cell}>Total Bill Amount: {totalBillAmount}</Text>
          <Text style={styles.cell}>Total Net Amount: {totalNetAmount}</Text>
        </View>
        <Text style={{ fontSize: 14, fontWeight: "bold" }}>
          From: {fromDate} To: {toDate}
        </Text>
        <Text style={{ fontSize: 14, fontWeight: "bold" }}>
          Generated by: {generatedBy}
        </Text>
      </Page>
    </Document>
  );
};

export default PDFReport;
